# Generated by Django 6.0 on 2025-12-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllGolfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hometown', models.CharField(blank=True, max_length=100)),
                ('tour', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('day_1_score_Masters26', models.IntegerField(blank=True, null=True)),
                ('day_2_score_Masters26', models.IntegerField(blank=True, null=True)),
                ('day_3_score_Masters26', models.IntegerField(blank=True, null=True)),
                ('day_4_score_Masters26', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
